### ISSUE TITLE
wrap is not work in this package?

### ISSUE THREAD

**Issue by radiorz** [theogravity/node-cache-manager-memcached-store#21]
![image](https://github.com/theogravity/node-cache-manager-memcached-store/assets/24271959/6468d6ec-b4c4-4766-b9f1-41947dc7cfae)

**Comment by theogravity** [comment]
mget isn't defined which is why you have that error

If the newer library supports it, feel free to implement it and open a PR

**Comment by radiorz** [comment]
#22

**Comment by theogravity** [comment]
Released as v5.0.0. Thanks!
