### ISSUE TITLE
Dependencies: xtend

### ISSUE THREAD

**Issue by RomanBurunkov** [theogravity/node-cache-manager-memcached-store#8]
Hi,

There is an xtend lib dependency in package.json, but I can't see any place in code where this lib is using.
Looks it should be removed.

**Comment by theogravity** [comment]
Feel free to open a PR

**Comment by RomanBurunkov** [comment]
Hi, PR opened

**Comment by RomanBurunkov** [comment]
Resolved with PR #9 .

**Comment by theogravity** [comment]
i'll publish in an hour or so

**Comment by RomanBurunkov** [comment]
Cool.

I've also add one more PR just to update dev deps to have the latest cache-manger version and also to exclude some vulnerability with jasmine.
